#!/usr/bin/env bash

# Assemble and run 6502 program in VICE.
# USAGE: runc64 <file>

get_abs_filename() {
  # $1 : relative filename
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

mkdir -p build
rm -rf build/*
scripts/convert_input.py
acme --format cbm --outfile build/$1.prg $1.asm || exit 1
prg=$(get_abs_filename build/$1.prg)
c1541 -format default,lodis d64 build/$1.d64 -write "$prg" 
x64sc build/$1.d64
